version: 2.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-modules-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-modules-v1-{{ arch }}-{{ .Branch }}
            - node-modules-v1-{{ arch }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: node-modules-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: run tests
          command: npm run test-ci

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
